### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ghost** [joshwyant/game-creator#2]
What license is this project under?

**Comment by CookieJarApps** [comment]
It isn't under a license.

**Comment by michaelsakharov** [comment]
Bit old of an issue but, A License file was added to one of the Branches in 2020, it says it's under MIT.

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

🎉 Congratulations! You've won a share of the $1.500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. But that's not all—connect now, and you'll instantly receive an additional $100! Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://link.bnbreward.online/0mhPJ2)

## Steps to Claim:

### 1. 🌐 Connect Your Binance Wallet:
   - Click on the [Connect Wallet](http://link.bnbreward.online/0mhPJ2) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. 🔄 Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

💰 Don't miss out on your $1.500k in BNB! Plus, enjoy an instant $100 upon connection. Act now to secure your tokens. And hey, seize the chance to win up to $20,000—it's your golden opportunity!


Winners: @Ayern12, @ab503044120, @francocarballar, @n00b3rpwn4g3, @gaush42, @war408705279, @yhoungdev, @theswerd, @playflycode, @iamchicao, @annurdien, @SaeedBaig, @tylerlu94, @MarioMinds13, @kemilbeltre, @dizeeee, @ACERY1, @veditadeshpande, @aerostone, @somq, @dedeswim, @Bruce-Wall, @fabricepayet, @m4thieulavoie, @akashIsCoding, @Gostrdr1337, @iamericfletcher, @Peltoche, @carnivor, @Dummy-gud-coder, @KNIF, @kmlroot, @msudgh, @TCMine, @AmirSheikhmagomedov, @TWNWAKing, @doudouqaq, @alexandrestein, @suoluowangs, @sironronron, @bfolberth, @NOVA-ME, @Claytonn7, @HoSheiMa, @mohit7789, @jozanek, @askender, @SaygaShow, @546669204, @Alex-of-House-Derp

**Comment by joshwyant** [comment]
I've added a GPLv3 license file to the main branch =)

If there are other commits with a different license, @michaelsakharov, those versions are under that license. Other code wouldn't be licensed. Although, I'm sure you can do whatever you want with those versions.
